### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by CEbbinghaus** [DarkReaper231/Incredibox#1]
I cannot believe I managed to find the source code. I was trying to decompile and reverse engineer the app but this has made it 100x easier.

How the hell did you manage to get it all in clear text?

**Comment by DarkReaper231** [comment]
I just bruteforced the obfuscation

**Comment by CEbbinghaus** [comment]
> I just bruteforced the obfuscation

That just sounds like a lot of work, time and effort spent on creating this. All the more reason to thank you <3 <3 <3

**Comment by DarkReaper231** [comment]
https://darkreaper231.github.io/Incredibox/

**Comment by CEbbinghaus** [comment]
Very cool. Love it

**Comment by DarkReaper231** [comment]
> Can you plz tell the procedure to run it

Get Visual Studio Code and this addon https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

Then you can just right click the index.html file and open it with live server
