### ISSUE TITLE
Imposible Language

### ISSUE THREAD

**Issue by Okeras** [DarkReaper231/Incredibox#2]
Everytime i open incredibox desktop it says "Impossible to load language settings, Please reload or force to quit te app then retry

**Comment by BUPPY2130** [comment]
same

**Comment by BovineBeta** [comment]
Try using a web server instead of opening  it by browser
![image](https://user-images.githubusercontent.com/83176414/185330047-34293dc1-384b-421a-a373-d8a7492f0cc2.png)

**Comment by BovineBeta** [comment]
Try using a web server instead of opening  it by browser
![image](https://user-images.githubusercontent.com/83176414/185330047-34293dc1-384b-421a-a373-d8a7492f0cc2.png)

**Comment by lunareclipse01313** [comment]
> Try using a web server instead of opening it by browser ![image](https://user-images.githubusercontent.com/83176414/185330047-34293dc1-384b-421a-a373-d8a7492f0cc2.png)

I still can't figure out how to open like this. I dont have the option to.

**Comment by BovineBeta** [comment]
https://github.com/DarkReaper231/Incredibox#:~:text=You%20can%20run%20it%20on%20apache,%20nginx%20or%20any%20other%20web%20server

I mean, you can try to set up a local http server.
That option comes from a vscode extension, called [Live Server](https://github.com/ritwickdey/vscode-live-server). This is not the only way, there are many other ways to quickly build a local http server.

For example, using python.
~~~shell
$ git clone https://github.com/DarkReaper231/Incredibox.git
$ cd Incredibox
$ python -m http.server
~~~
![python -m http.server](https://user-images.githubusercontent.com/83176414/229265270-151608b1-0ed1-41fd-9087-486433c3343e.png)

**Comment by BovineBeta** [comment]
> > Try using a web server instead of opening it by browser ![image](https://user-images.githubusercontent.com/83176414/185330047-34293dc1-384b-421a-a373-d8a7492f0cc2.png)
> 
> I still can't figure out how to open like this. I dont have the option to.

https://github.com/DarkReaper231/Incredibox#:~:text=You%20can%20run%20it%20on%20apache,%20nginx%20or%20any%20other%20web%20server

I mean, you can try to set up a local http server.
That option comes from a vscode extension, called [Live Server](https://github.com/ritwickdey/vscode-live-server). This is not the only way, there are many other ways to quickly build a local http server.

For example, using python.
~~~shell
$ git clone https://github.com/DarkReaper231/Incredibox.git
$ cd Incredibox
$ python -m http.server
~~~
![python -m http.server](https://user-images.githubusercontent.com/83176414/229265270-151608b1-0ed1-41fd-9087-486433c3343e.png)

**Comment by DarkReaper231** [comment]
> Everytime i open incredibox desktop it says "Impossible to load language settings, Please reload or force to quit te app then retry

You have to
