### ISSUE TITLE
v9 when?

### ISSUE THREAD

**Issue by te-agma-at** [DarkReaper231/Incredibox#6]
incredibox v9 is out lol

**Comment by DarkReaper231** [comment]
v9 is obfuscated. I have to choices. Try to deobfuscate it or merge it into the existing code base as is.

**Comment by DarkReaper231** [comment]
> incredibox v9 is out lol

Apparently it wasn't that hard to use what exists in 0.5.4 and backport V9 to this version, I have just pushed V9, enjoy!
https://darkreaper231.github.io/Incredibox/
